//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.28 at 06:57:51 PM CST 
//


package com.linyeah.erp.orderdescschema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuthUserName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="10"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AuthPassword">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="10"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AuthtokenCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ProductName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OperationCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0001"/>
 *               &lt;enumeration value="0002"/>
 *               &lt;enumeration value="0003"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CustSequence">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="5"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Products">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://erp.linyeah.com/OrderDescSchema.xsd}OrderItemGroup" maxOccurs="5"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authUserName",
    "authPassword",
    "authtokenCode",
    "productName",
    "operationCode",
    "custSequence",
    "products"
})
@XmlRootElement(name = "OrderDesc")
public class OrderDesc {

    @XmlElement(name = "AuthUserName", required = true)
    protected String authUserName;
    @XmlElement(name = "AuthPassword", required = true)
    protected String authPassword;
    @XmlElement(name = "AuthtokenCode", required = true)
    protected String authtokenCode;
    @XmlElement(name = "ProductName", required = true)
    protected String productName;
    @XmlElement(name = "OperationCode", required = true)
    protected String operationCode;
    @XmlElement(name = "CustSequence", required = true)
    protected String custSequence;
    @XmlElement(name = "Products", required = true)
    protected OrderDesc.Products products;

    /**
     * Gets the value of the authUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthUserName() {
        return authUserName;
    }

    /**
     * Sets the value of the authUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthUserName(String value) {
        this.authUserName = value;
    }

    /**
     * Gets the value of the authPassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthPassword() {
        return authPassword;
    }

    /**
     * Sets the value of the authPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthPassword(String value) {
        this.authPassword = value;
    }

    /**
     * Gets the value of the authtokenCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthtokenCode() {
        return authtokenCode;
    }

    /**
     * Sets the value of the authtokenCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthtokenCode(String value) {
        this.authtokenCode = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the operationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * Sets the value of the operationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationCode(String value) {
        this.operationCode = value;
    }

    /**
     * Gets the value of the custSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustSequence() {
        return custSequence;
    }

    /**
     * Sets the value of the custSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustSequence(String value) {
        this.custSequence = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDesc.Products }
     *     
     */
    public OrderDesc.Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDesc.Products }
     *     
     */
    public void setProducts(OrderDesc.Products value) {
        this.products = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://erp.linyeah.com/OrderDescSchema.xsd}OrderItemGroup" maxOccurs="5"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "orderItemGroup"
    })
    public static class Products {

        @XmlElement(name = "Product", required = true)
        protected List<OrderDesc.Products.Product> orderItemGroup;

        /**
         * Gets the value of the orderItemGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderItemGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOrderItemGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OrderDesc.Products.Product }
         * 
         * 
         */
        public List<OrderDesc.Products.Product> getOrderItemGroup() {
            if (orderItemGroup == null) {
                orderItemGroup = new ArrayList<OrderDesc.Products.Product>();
            }
            return this.orderItemGroup;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Sequence" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="ProdCode">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;length value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ProdName">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="50"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="ProdWidth" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="ProdHeight" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="ProdNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="PrintMark" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Bleeding" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="CustSizeFlag">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="Y|N"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="HasCover">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="Y|N"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CovMatriCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CovSinOrDblSide">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="0|1|"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CovpageColor">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;pattern value="0|1|"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CovPrtProcesse1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CovPrtProcesse2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CovPrtProcesse3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnMatriCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnSinOrDblSide">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;pattern value="0|1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="InnpageColor">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;pattern value="0|1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="InnpageNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *               &lt;minInclusive value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="InnPrtProcesse1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnPrtProcesse2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnPrtProcesse3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CoverFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CoverFileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnerFile" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InnerFileSize" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "sequence",
            "prodCode",
            "prodName",
            "prodWidth",
            "prodHeight",
            "prodNumber",
            "printMark",
            "bleeding",
            "custSizeFlag",
            "hasCover",
            "covMatriCode",
            "covSinOrDblSide",
            "covpageColor",
            "covPrtProcesse1",
            "covPrtProcesse2",
            "covPrtProcesse3",
            "innMatriCode",
            "innSinOrDblSide",
            "innpageColor",
            "innpageNumber",
            "innPrtProcesse1",
            "innPrtProcesse2",
            "innPrtProcesse3",
            "coverFile",
            "coverFileSize",
            "innerFile",
            "innerFileSize"
        })
        public static class Product {

            @XmlElement(name = "Sequence", required = true)
            protected BigInteger sequence;
            @XmlElement(name = "ProdCode", required = true)
            protected String prodCode;
            @XmlElement(name = "ProdName", required = true)
            protected String prodName;
            @XmlElement(name = "ProdWidth", required = true)
            protected BigInteger prodWidth;
            @XmlElement(name = "ProdHeight", required = true)
            protected BigInteger prodHeight;
            @XmlElement(name = "ProdNumber", required = true)
            protected BigInteger prodNumber;
            @XmlElement(name = "PrintMark", required = true)
            protected String printMark;
            @XmlElement(name = "Bleeding", required = true)
            protected BigInteger bleeding;
            @XmlElement(name = "CustSizeFlag", required = true)
            protected String custSizeFlag;
            @XmlElement(name = "HasCover", required = true)
            protected String hasCover;
            @XmlElement(name = "CovMatriCode", required = true)
            protected String covMatriCode;
            @XmlElement(name = "CovSinOrDblSide", required = true)
            protected String covSinOrDblSide;
            @XmlElement(name = "CovpageColor", required = true)
            protected String covpageColor;
            @XmlElement(name = "CovPrtProcesse1", required = true)
            protected String covPrtProcesse1;
            @XmlElement(name = "CovPrtProcesse2", required = true)
            protected String covPrtProcesse2;
            @XmlElement(name = "CovPrtProcesse3", required = true)
            protected String covPrtProcesse3;
            @XmlElement(name = "InnMatriCode", required = true)
            protected String innMatriCode;
            @XmlElement(name = "InnSinOrDblSide", required = true)
            protected BigInteger innSinOrDblSide;
            @XmlElement(name = "InnpageColor", required = true)
            protected BigInteger innpageColor;
            @XmlElement(name = "InnpageNumber", required = true)
            protected BigInteger innpageNumber;
            @XmlElement(name = "InnPrtProcesse1", required = true)
            protected String innPrtProcesse1;
            @XmlElement(name = "InnPrtProcesse2", required = true)
            protected String innPrtProcesse2;
            @XmlElement(name = "InnPrtProcesse3", required = true)
            protected String innPrtProcesse3;
            @XmlElement(name = "CoverFile", required = true)
            protected String coverFile;
            @XmlElement(name = "CoverFileSize", required = true)
            protected String coverFileSize;
            @XmlElement(name = "InnerFile", required = true)
            protected String innerFile;
            @XmlElement(name = "InnerFileSize", required = true)
            protected String innerFileSize;

            /**
             * Gets the value of the sequence property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getSequence() {
                return sequence;
            }

            /**
             * Sets the value of the sequence property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setSequence(BigInteger value) {
                this.sequence = value;
            }

            /**
             * Gets the value of the prodCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProdCode() {
                return prodCode;
            }

            /**
             * Sets the value of the prodCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProdCode(String value) {
                this.prodCode = value;
            }

            /**
             * Gets the value of the prodName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProdName() {
                return prodName;
            }

            /**
             * Sets the value of the prodName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProdName(String value) {
                this.prodName = value;
            }

            /**
             * Gets the value of the prodWidth property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getProdWidth() {
                return prodWidth;
            }

            /**
             * Sets the value of the prodWidth property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setProdWidth(BigInteger value) {
                this.prodWidth = value;
            }

            /**
             * Gets the value of the prodHeight property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getProdHeight() {
                return prodHeight;
            }

            /**
             * Sets the value of the prodHeight property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setProdHeight(BigInteger value) {
                this.prodHeight = value;
            }

            /**
             * Gets the value of the prodNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getProdNumber() {
                return prodNumber;
            }

            /**
             * Sets the value of the prodNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setProdNumber(BigInteger value) {
                this.prodNumber = value;
            }

            /**
             * Gets the value of the printMark property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrintMark() {
                return printMark;
            }

            /**
             * Sets the value of the printMark property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrintMark(String value) {
                this.printMark = value;
            }

            /**
             * Gets the value of the bleeding property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBleeding() {
                return bleeding;
            }

            /**
             * Sets the value of the bleeding property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBleeding(BigInteger value) {
                this.bleeding = value;
            }

            /**
             * Gets the value of the custSizeFlag property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCustSizeFlag() {
                return custSizeFlag;
            }

            /**
             * Sets the value of the custSizeFlag property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCustSizeFlag(String value) {
                this.custSizeFlag = value;
            }

            /**
             * Gets the value of the hasCover property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHasCover() {
                return hasCover;
            }

            /**
             * Sets the value of the hasCover property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHasCover(String value) {
                this.hasCover = value;
            }

            /**
             * Gets the value of the covMatriCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovMatriCode() {
                return covMatriCode;
            }

            /**
             * Sets the value of the covMatriCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovMatriCode(String value) {
                this.covMatriCode = value;
            }

            /**
             * Gets the value of the covSinOrDblSide property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovSinOrDblSide() {
                return covSinOrDblSide;
            }

            /**
             * Sets the value of the covSinOrDblSide property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovSinOrDblSide(String value) {
                this.covSinOrDblSide = value;
            }

            /**
             * Gets the value of the covpageColor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovpageColor() {
                return covpageColor;
            }

            /**
             * Sets the value of the covpageColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovpageColor(String value) {
                this.covpageColor = value;
            }

            /**
             * Gets the value of the covPrtProcesse1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovPrtProcesse1() {
                return covPrtProcesse1;
            }

            /**
             * Sets the value of the covPrtProcesse1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovPrtProcesse1(String value) {
                this.covPrtProcesse1 = value;
            }

            /**
             * Gets the value of the covPrtProcesse2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovPrtProcesse2() {
                return covPrtProcesse2;
            }

            /**
             * Sets the value of the covPrtProcesse2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovPrtProcesse2(String value) {
                this.covPrtProcesse2 = value;
            }

            /**
             * Gets the value of the covPrtProcesse3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCovPrtProcesse3() {
                return covPrtProcesse3;
            }

            /**
             * Sets the value of the covPrtProcesse3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCovPrtProcesse3(String value) {
                this.covPrtProcesse3 = value;
            }

            /**
             * Gets the value of the innMatriCode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnMatriCode() {
                return innMatriCode;
            }

            /**
             * Sets the value of the innMatriCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnMatriCode(String value) {
                this.innMatriCode = value;
            }

            /**
             * Gets the value of the innSinOrDblSide property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getInnSinOrDblSide() {
                return innSinOrDblSide;
            }

            /**
             * Sets the value of the innSinOrDblSide property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setInnSinOrDblSide(BigInteger value) {
                this.innSinOrDblSide = value;
            }

            /**
             * Gets the value of the innpageColor property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getInnpageColor() {
                return innpageColor;
            }

            /**
             * Sets the value of the innpageColor property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setInnpageColor(BigInteger value) {
                this.innpageColor = value;
            }

            /**
             * Gets the value of the innpageNumber property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getInnpageNumber() {
                return innpageNumber;
            }

            /**
             * Sets the value of the innpageNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setInnpageNumber(BigInteger value) {
                this.innpageNumber = value;
            }

            /**
             * Gets the value of the innPrtProcesse1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnPrtProcesse1() {
                return innPrtProcesse1;
            }

            /**
             * Sets the value of the innPrtProcesse1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnPrtProcesse1(String value) {
                this.innPrtProcesse1 = value;
            }

            /**
             * Gets the value of the innPrtProcesse2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnPrtProcesse2() {
                return innPrtProcesse2;
            }

            /**
             * Sets the value of the innPrtProcesse2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnPrtProcesse2(String value) {
                this.innPrtProcesse2 = value;
            }

            /**
             * Gets the value of the innPrtProcesse3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnPrtProcesse3() {
                return innPrtProcesse3;
            }

            /**
             * Sets the value of the innPrtProcesse3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnPrtProcesse3(String value) {
                this.innPrtProcesse3 = value;
            }

            /**
             * Gets the value of the coverFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCoverFile() {
                return coverFile;
            }

            /**
             * Sets the value of the coverFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCoverFile(String value) {
                this.coverFile = value;
            }

            /**
             * Gets the value of the coverFileSize property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCoverFileSize() {
                return coverFileSize;
            }

            /**
             * Sets the value of the coverFileSize property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCoverFileSize(String value) {
                this.coverFileSize = value;
            }

            /**
             * Gets the value of the innerFile property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnerFile() {
                return innerFile;
            }

            /**
             * Sets the value of the innerFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnerFile(String value) {
                this.innerFile = value;
            }

            /**
             * Gets the value of the innerFileSize property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInnerFileSize() {
                return innerFileSize;
            }

            /**
             * Sets the value of the innerFileSize property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInnerFileSize(String value) {
                this.innerFileSize = value;
            }

        }

    }

}
